services:

  minio:
    image: minio/minio
    container_name: minio
    command: 
     - server
     - /data
    environment:
     - MINIO_ROOT_USER=minio
     - MINIO_ROOT_PASSWORD=miniopass
    network_mode: host
