services:

  notification:
    image: "ashupednekar535/otelexamples:notification"
    container_name: notification
    environment:
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PASS=${SMTP_PASS}
      - NATS_URL=localhost:30042
    network_mode: host

  payment:
    image: "ashupednekar535/otelexamples:payment"
    container_name: payment 
    environment:
      - PAYMENT_PORT=7001
      - NATS_URL=localhost:30042
    network_mode: host

