services:

  notification:
    image: "ashupednekar535/otelexamples:notification"
    container_name: notification
    environment:
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PASS=${SMTP_PASS}
      - NATS_URL=localhost:30042
    network_mode: host

  payment:
    image: "ashupednekar535/otelexamples:payment"
    container_name: payment 
    environment:
      - PAYMENT_PORT=7001
      - NATS_URL=localhost:30042
    network_mode: host

  invoice:
    image: "ashupednekar535/otelexamples:invoice"
    container_name: invoice
    network_mode: host
  
  order:
    image: "ashupednekar535/otelexamples:order"
    container_name: order
    env_file: 
    - order/config.env
    network_mode: host

  order-consumer:
    image: "ashupednekar535/otelexamples:order"
    container_name: order-consumer
    command: 
    - python
    - consumer.py
    env_file: 
    - order/config.env
    network_mode: host

  minio:
    image: minio/minio
    container_name: minio
    command: 
     - server
     - /data
    environment:
     - MINIO_ROOT_USER=minio
     - MINIO_ROOT_PASSWORD=miniopass
    network_mode: host

