[package]
name = "payment"
version = "0.1.0"
edition = "2021"

[dependencies]
async-nats = "0.37.0"
axum = "0.7.7"
serde = { version = "1.0.211", features = ["derive"] }
serde_json = "1.0.132"
tokio = { version = "1.41.0", features = ["full"] }
